services:
  app:
    image: python:3.11-slim
    container_name: test_app
    volumes:
      - ./app.py:/app/app.py
    working_dir: /app
    command: python app.py

  waf:
    image: coreruleset/modsecurity-crs:nginx
    container_name: test_waf
    depends_on:
      - app
    volumes:
      - ./waf/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./waf/modsecurity:/etc/nginx/modsecurity
    ports:
      - "8080:80"

